### ISSUE TITLE
How to register $refs while using this package?

### ISSUE THREAD

**Issue by phao5814** [ktsn/vue-typed-mixins#10]
I was reading through this [GitHub issue](https://github.com/vuejs/vue-class-component/issues/94#issuecomment-427645553), which showed that the following syntax would allow Typescript to recognise $refs.

```
<script lang="ts">
import Vue, { VueConstructor } from 'vue';

export default (Vue as VueConstructor<Vue &
  { $refs: 
    { ul: HTMLElement },
  }
>).extend({
  name: 'HelloExtend',
···
methods: {
    changeText() {
      this.$refs.ul.innerHTML = 'blablabla';
    },
```

How can I achieve the above while using this package in order to use Vue mixins? Not to sure what the notation should look like.

**Comment by ktsn** [comment]
Unfortunately, there is no clean way to do that with option style API. Possible approaches are:

1. You can cast it when you use it

  ```ts
  changeText() {
    const ul = this.$refs.ul as HTMLElement
    ul.innerHTML = '...'
  }
  ```

2. Use composition API

  ```ts
  setup() {
    const ul = ref<HTMLElement | null>(null)

    function changeText() {
      if (ul.value) {
      }
    }

    return {
      ul
    }
  }
  ```

**Comment by phao5814** [comment]
I see. Thanks for your response. On a related note, my specific problem is actually best demonstrated by the example below. Do you have any advice on how I can cast `this.$refs["component"]` to `MyComponent`?

```
<template>
    <my-component ref="component"/>
</template>

<script lang="ts">
import MyComponent from "@/components/my-component.vue";

export default mixins(SomeMixin, SomeOtherMixin).extend({
    components: {
        MyComponent,
    },
    methods: {
        async someMethod() {
            // How do I cast the following variable as type "MyComponent"?
            const component = this.$refs["component"];
            console.log(component.$props);
        },
    },
});
</script>
```
