### ISSUE TITLE
Global Mixins

### ISSUE THREAD

**Issue by stoically** [ktsn/vue-typed-mixins#3]
Thanks for your worked on typed mixins!

Not sure if that's in the scope of this project, but would it be possible to have globally defined typed mixins? Because if I use `Vue.mixin` in the root of the project, those methods are available everywhere, but are unfortunately not typed. If it's not in the scope, I'd greatly appreciate hints on how to achieve that manually.

**Comment by ktsn** [comment]
This is not a scope of this lib. You can augment base component instance type by yourself: https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins
