### ISSUE TITLE
empty tag doesnt work in some browsers and unresolved functions,

### ISSUE THREAD

**Issue by SeyyedKhandon** [ktsn/vue-typed-mixins#4]
i had a problem using mixins in vuejs with typescript, i asked and someone  on stack told me to use vue-typed-mixins. so i used this and it solved the problem, but another problem exposes, which i asked with picture in stackoverflow, 
[https://stackoverflow.com/questions/59828104/ts2339-error-how-to-use-typescript-mixin-in-vuejs-project](https://stackoverflow.com/questions/59828104/ts2339-error-how-to-use-typescript-mixin-in-vuejs-project)
as you can see in the  bleow picture, is there any way to fix this problem?
![image](https://user-images.githubusercontent.com/59599950/72874078-73325d00-3d06-11ea-87b0-cdbce486b467.png)

**Comment by ktsn** [comment]
It's not related to vue-typed-mixin...
Looks like there are some false-positive error on your linter rules. Try disabling such rules.

**Comment by SeyyedKhandon** [comment]
i dont think it's about linter, because when i installed and use it, this new error happened, and when i dont use it, the error will gone,, i want to just fix this problem,

**Comment by ktsn** [comment]
Then please provide a reproduction to confirm if it is really vue-typed-mixin problem.
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by SeyyedKhandon** [comment]
```
C:\Users\User\Desktop\New folder
λ vue create typed


Vue CLI v4.1.2
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, Vuex, CSS Pre-processors, Linter, Unit
? Use class-style component syntax? No
? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with node-sass)
? Pick a linter / formatter config: Basic
? Pick additional lint features: (Press <space> to select, <a> to toggle all, <i> to invert selection)Lint on save
? Pick a unit testing solution: Jest
? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```
first version: (which is good in detecting function, but has problem in detecting mixins)
![image](https://user-images.githubusercontent.com/59599950/72964730-eb188a00-3dcf-11ea-94ed-0301f5db4aed.png)


second version:(which is good in detecting mixins functions inside of script tag, but has problem in detecting functions in the template tag):

![image](https://user-images.githubusercontent.com/59599950/72965133-ca9cff80-3dd0-11ea-9c0b-36353abe52d8.png)

**Comment by ktsn** [comment]
Well, you still don't provide reproduction... Screenshot is not a reproduction as I cannot confirm the problem on my end. Please read [the link](https://stackoverflow.com/help/minimal-reproducible-example) carefully and provide an example GitHub repo, for example.

**Comment by SeyyedKhandon** [comment]
this is a reprex:
https://github.com/SeyyedKhandon/reprex-vue-typed-mixins-unresolved-function-error

**Comment by ktsn** [comment]
There is no error on my side. Please make sure to disable all your editor extension and boil down the cause.

My steps taken are:

1. Clone your reproduction.
2. yarn install
3. Open it on VSCode.
4. Disable all extension except Vetur.
5. Open App.vue and confirmed there is no error.

<img width="403" alt="Screenshot 2020-01-23 at 5 50 46 PM" src="https://user-images.githubusercontent.com/2194624/72969549-06ec5200-3e09-11ea-8057-3c964799af9c.png">


I also saw the component type is correctly inferred. Looks like It is not the problem on this lib.

<img width="995" alt="Screenshot 2020-01-23 at 5 50 59 PM" src="https://user-images.githubusercontent.com/2194624/72969548-0653bb80-3e09-11ea-97ed-610377a456c5.png">

**Comment by SeyyedKhandon** [comment]
first of all, i'm used the latest version of web storm in the above pictures,
second i also ran this project as you said with vscode and using only veuter . and it cannot show the difintion and so there is no intellisense for it, not in the template nor in script tag...:
![image](https://user-images.githubusercontent.com/59599950/72971573-2cfcfc80-3ddf-11ea-9c30-c51372438a4e.png)

**Comment by ktsn** [comment]
Vetur still does not support typings so the not working completion is expected behavior currently. FYI, this issue will be fixed via this PR.
https://github.com/vuejs/vetur/pull/1446

As for WebStorm, then, it's the issue of WebStorm which probably the same reason that it does not use type info for template analysis.

In any cases, there is nothing I can do for it with vue-typed-mixin, unfortunately.

Please file in IntelliJ's issue tracker to solve this problem.
https://github.com/JetBrains/intellij-plugins/tree/master/vuejs

**Comment by SeyyedKhandon** [comment]
i will post the issue where you said, but my question is, when i use vue-typed-mixins the problem exposes in the webstorm. so when i dont use it, there is no problem. this is telling that the problem cause maybe is the vue-typed-mixins which when you use it make these problems.
because of this, i think maybe there is something we should do in vue-typed-mixins to prevent these unresolved functions, to webstorm and veutr working in the normal way, therefore can detect added mixin's  methods and datas ...
