### ISSUE TITLE
How to write mixin augmentations

### ISSUE THREAD

**Issue by kelunik** [ktsn/vue-typed-mixins#6]
Thanks for the package! I confirmed it works great if I write my mixins like it's outlined in the README. However, I'm having issues coming up with a module augmentation that works for an external mixin defined in a package I use.

https://github.com/dobromir-hristov/vuelidate-error-extractor/blob/9590f9b8c7ba28338276a68a2545c5e798666113/src/single-error-extractor-mixin.js

I've tried the following, but it doesn't work. I guess I have to use `ComponentOptions` and provide the generics there? I've tried that, but haven't succeeded.

Do you have any advice?

```ts
declare module 'vuelidate-error-extractor' {
   import { PluginFunction } from 'vue/types/plugin';
   import { Validation } from 'vuelidate';

   // eslint-disable-next-line @typescript-eslint/naming-convention
   const VuelidateErrorExtractor: PluginFunction<any>;

   export default VuelidateErrorExtractor;

   // eslint-disable-next-line @typescript-eslint/class-name-casing
   export class singleErrorExtractorMixin extends Vue {
      readonly events: any;

      readonly name: string;

      readonly isValid: boolean;

      readonly hasErrors: boolean;

      readonly activeErrors: Validation[];

      readonly activeErrorMessages: string[];

      readonly preferredValidator: Validation;

      getErrorMessage(key: string, params: object): string;
   }
}
```

**Comment by ktsn** [comment]
If you mean how to augment vue component type and component options type, Vue official doc states it.
https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins

If you mean how to extend component type by using augment field, it's impossible. We should use composition api instead of mixins.
https://github.com/vuejs/composition-api

**Comment by kelunik** [comment]
Thanks for the fast response! I'm aware of the possible global augmentation. What I'm looking for is writing down the type definition that the compiler automatically infers for the following type:

```
const Foo = Vue.extend({
  data() {
    return {
      foo: 'test'
    }
  }
});
```

This could then be placed into an augmentation file to augment an external mixin, no?

I'm looking forward to the composition API, but I'm currently following the advice to avoid using it on production for now.

**Comment by ktsn** [comment]
What do you mean by "augment an external mixin"? I'm still not sure what you want to do, sorry.

**Comment by kelunik** [comment]
Instead of defining the mixin in my own codebase like in the README, I'm using https://github.com/dobromir-hristov/vuelidate-error-extractor as dependency. As that package comes without type definitions, I tried adding those myself with an `vuelidate-error-extractor.d.ts` file. As there aren't any type definitions, I need to add at least an `declare module 'vuelidate-error-extractor';` in there, but I'd like to provide the types as if `vuelidate-error-extractor` was written in typescript.

Does that make it clear what I'm trying to achive?
