### ISSUE TITLE
Typing works, but methods can't be called?

### ISSUE THREAD

**Issue by matthew-dean** [ktsn/vue-typed-mixins#7]
I have a mixin like this:
```ts
export default Vue.extend({
    data() {
        return {
            message: {
                text: '',
                type: MESSAGE_TYPE.INFO,
            }
        }
    },

    methods: {
        info(msg: string) {
            console.log(msg)
            this.message.type = MESSAGE_TYPE.INFO
            this.message.text = msg
        },

        error(msg: string) {
            console.error(msg)
            this.message.type = MESSAGE_TYPE.ERROR
            this.message.text = msg
        }
    }
})
```
I had issues with typing until I used this library; however, it doesn't seem to mix the methods in like a normal mixin. I'm getting errors in a component that's like `Mixin(Messages).extend({})`

When I call `this.error()` or `this.info()`, it says those methods are not functions.

This also fails:
```ts
Mixin(Messages).extend({ mixins: [Messages] })
```
The mixins are still typed and still not callable.

However this works:
```ts
Vue.extend({
  mixins: [Messages]
  methods: {
    someMethod() {
      //@ts-ignore
      this.error('error')
    }
  }
})
```

So, somehow this library not only makes mixin methods not callable, but prevents mixins from being normally registered and being callable.

(Btw, if it helps, this is on Vue v1. Vue v2 is unfortunately not available.)

**Comment by ktsn** [comment]
Thank you for filing the issue.
Please provide a minimal and self-contained reproduction to confirm the issue.

See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ktsn** [comment]
Closing as repro is not provided.
