### ISSUE TITLE
with IntelliJ Editors (PHPStorm eg) it breaks SFC template support (not compilation)

### ISSUE THREAD

**Issue by opgbaudouin** [ktsn/vue-typed-mixins#8]
When using the code inside PHPStorm all 'Vue' SFC support fails in the IDE. 

First of all Template support with TS inside PHPStorm in SFC is not great already - however it was always being to detect the used included components. 

e.g.
```typescript
<template>
     <div>
        <external-component/>   
        <!-- without the mixin the IDE knows what this is and can navigate and give support, with the mixins.extend the IDE has no idea what this is --> 
    </div>
</template>

<script lang="ts">
    import mixins from 'vue-typed-mixins';
   import ExternalComponent from "@/components/ExternalComponent";
   const basicMixin = Vue.extend({
        computed: {
            isTest(): boolean {
                return true;
            }
        } 
    });
   
 export default mixins(basicMixin).extend({
     components: {
           ExternalComponent 
     },
    computed: {
          hasTest(): boolean {
             return this.isTest; //fully supported TS support in IDE!
         }
    }
}); 
</script>
```
So i either have the use the functions to have strong typing in code, but loose all IDE support. 

It's either something not quite right with the TS types or IDE is not compatible... 

Update: i found this related: https://youtrack.jetbrains.com/issue/WEB-43243

The 'temporary solution' is:
```typescript
const Vue = mixins(basicMixin)
export default Vue.extend({....})
```
This obviously 'abuses' what the IDE thinks 'Vue' is but is fully valid TS.

**Comment by ktsn** [comment]
This is IDE's issue that it doesn't seem to utilize type information. There is nothing I can do for it from this lib.
