### ISSUE TITLE
Vue-typed-mixins  destroys this context in mounted & created method

### ISSUE THREAD

**Issue by Patrick-Spiegel** [ktsn/vue-typed-mixins#9]
```
mixins(MyMixin).extend({
  methods: {
    Test() {
      console.log("Test"); 
    }
  },
  mounted() {
    this.Test(); // doesn't work anymore
    const a = this.myMixinMember; // does not work either
  }
})
```
![image](https://user-images.githubusercontent.com/35311793/86444699-726c1100-bd11-11ea-92f0-75d84433252f.png)

**Comment by Patrick-Spiegel** [comment]
If I copy your mixins class into my code then its working without any changes...

**Comment by ktsn** [comment]
Thank you for filing the issue.
Please provide a minimal and self-contained reproduction to confirm the issue.

See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Patrick-Spiegel** [comment]
The issue was a prop that didnt have a return type defined. Your package works perfectly as it should. 👍
